### ISSUE TITLE
Fix for react-router context.

### ISSUE THREAD

**Issue by steida** [gaearon/react-pure-render#1]
How do you workaround issue with react-router context? Este.js approach is https://github.com/steida/este/blob/5b26613ec81c3fefce19734d349f24f15ffe1373/src/client/components/purecomponent.react.js#L13

**Comment by gaearon** [comment]
Hmm. I guess one way to handle this is to always return `true` if `this.context` is an object. Does this make sense?

**Comment by steida** [comment]
Isn't context always object? I believe it is. This workaround is good enough.

**Comment by gaearon** [comment]
I don't want to have lib-specific workaround to be honest. Also, this won't help someone struggling with the same problem, but with some other context-reliant library like Moriarty.

**Comment by gaearon** [comment]
Oh, I get it now. Your workaround is functioning because you explicitly put `contextTypes` on it.
As I said I don't want to special-case RR here, so I'm going to add a note explaining the problem instead.

**Comment by gaearon** [comment]
Closing via https://github.com/gaearon/react-pure-render/commit/3365677c308a8bd548c596f8f7e3964cecf1388c.

Thanks a lot for the input. I understand your solution is more pragmatic, but it wouldn't work with a function anyway. If used on base class, people would be able to overwrite it by mistake. So it's not perfect either.

**Comment by steida** [comment]
You are welcome. Este.js needs it because stack must work out of the box. I like you added very thoughtful explanation.
