### ISSUE TITLE
Function equality?

### ISSUE THREAD

**Issue by rclai** [gaearon/react-pure-render#12]
This might be a dumb question, but if I use `shouldPureComponentUpdate` and one of the props is a function passed from the parent, shouldn't the function be equal? Or is it impossible to compare functions? I noticed that if I stop passing `handleRemoveTodo` to the `TodoItem`s, the `shouldComponentUpdate` will return false, otherwise, it keeps returning true. I'm testing the logging by adding and removing items.

```
import React, { Component, PropTypes } from 'react';
import shouldPureComponentUpdate from 'react-pure-render/function';

class TodoList extends Component {
  handleRemoveTodo(todoId, e) {
    e.preventDefault();
    removeTodo(todoId);
  }

  render() {
    const { todos } = this.props;
    return (
      <ul>
        {todos.map((todo) => {
          return (
            <TodoItem 
              key={todo._id} 
              onRemove={this.handleRemoveTodo.bind(this, todo._id)}
              {...todo} />  
          );
        })}
      </ul>        
    );
  }
}

class TodoItem extends Component {
  shouldComponentUpdate(...args) {
    const updateMe= shouldPureComponentUpdate.apply(this, args);
    console.log(`Todo ${this.props._id} returned ${updateMe}`)
    return updateMe;
  }

  render() {
    const { todoText } = this.props;
    return (
      <li>
        <a href="#" onClick={this.props.onRemove}>x</a>
        {todoText}
      </li>  
    );
  }
}
```

**Comment by rclai** [comment]
Oh turns out I'm supposed to bind the handler function on the `TodoItem` component instead of `TodoLists`.

**Comment by bzums** [comment]
@rclai how exactly did you solve this issue? I am currently facing the same problem: a callback function passed via props leads to always rerendering the component which is not reasonable, is it?

**Comment by rclai** [comment]
I'm not quite sure how it all works, but you see how I bound the `onRemove` function to the `TodoList` component before I passed it to the `TodoItem`? Apparently, doing that changed the reference of the function, causing it to not be equal. So what I did was not bind it there but bound it after it was passed. I don't quite remember the details but it was something along the lines of this:

```jsx
import React, { Component, PropTypes } from 'react';
import shouldPureComponentUpdate from 'react-pure-render/function';

class TodoList extends Component {
  handleRemoveTodo(todoId, e) {
    e.preventDefault();
    removeTodo(todoId);
  }

  render() {
    const { todos } = this.props;
    return (
      <ul>
        {todos.map((todo) => {
          return (
            <TodoItem 
              key={todo._id} 
              onRemove={this.handleRemoveTodo}
              {...todo} />  
          );
        })}
      </ul>        
    );
  }
}

class TodoItem extends Component {
  shouldComponentUpdate(...args) {
    const updateMe= shouldPureComponentUpdate.apply(this, args);
    console.log(`Todo ${this.props._id} returned ${updateMe}`)
    return updateMe;
  }
  handleRemove(id) {
    this.props.onRemove(id);
  }
  render() {
    const { todoText, _id } = this.props;
    return (
      <li>
        <a href="#" onClick={this.handleRemove.bind(this, _id)}>x</a>
        {todoText}
      </li>  
    );
  }
}
```

Also, after second thought, I think I might know what the issue is now. I think the issue wasn't entirely that I bound it before I passed it, but that I bound it with a parameter, which caused its reference to change. Now I have to test that out.

**Comment by bzums** [comment]
Well, if you do not bind `this` then you cannot access it in the callback which is quite a problem ;) In your second example you are assuming a global `removeTodo` function which is quite optimistic ;)

I really see a problem with function inequality and am wondering how this is solved or whether I am missing a point...

**Comment by rclai** [comment]
Have you already tested binding with no parameters.

**Comment by rclai** [comment]
Try pre-binding your methods like this: https://github.com/brentvatne/react-native-video/blob/feature/android-support/Video.js#L21-L30

**Comment by bzums** [comment]
```
class Checkbox extends React.Component {

  constructor() {
    super();
    this.handleChange = this.handleChange.bind(this);
  }

  shouldComponentUpdate(nextProps, nextState) {
    let update = shallowEqual(this.props, nextProps);
    console.log(update);
    return update;
  }

  handleChange(e) {
    this.props.onChange(e);
  }

  render() {
    const { label, value } = this.props;

    return (
        <Input
          type="checkbox"
          label={label}
          checked={value}
          onChange={this.handleChange} />
    );
  }
}
```

Still, shallowEqual always return `false`...

**Comment by rclai** [comment]
How is `this.props.onChange` being passed? Is that function also pre-bound?
