### ISSUE TITLE
Shallow plus one compare?

### ISSUE THREAD

**Issue by mindjuice** [gaearon/react-pure-render#16]
I've got a few components where I would, ideally, prefer to pass in an array or an object as a prop, for example a range:

    <MyComponent range={[0, 100]}/>  // MyComponent uses react-pure-render

Right now, I of course get a unique object each time ``MyComponent`` is called, so the pure rendering of MyComponent is negated.

I've "fixed" this in other places by splitting the props to things like ``rangeStart`` and ``rangeEnd``, or by declaring a ``const myRange = [0,100];`` earlier in the .js file and passing that in instead, but those are unsatisfying.

I'd like to be able to specify that some props get compared one-level deeper.

So maybe in ``MyComponent`` it changes to something like this:

    shouldComponentUpdate = shouldPureComponentUpdate( { compare: { range: 1 } } );

or if we only want to allow one-level extra checking:

    shouldComponentUpdate = shouldPureComponentUpdate( { compare: [ 'range' ] } );

Essentially the function returned by ``shouldPureComponentUpdate`` would check each key in ``deepCompare`` to the specified level and perform the normal shallow check for the rest of the object.

Would you be open to a PR for something like this or do you prefer to keep ``react-pure-render`` simple?

Anyone have any better suggestions for handling this case?

**Comment by leesei** [comment]
I think you use case is not covered by `react-pure-render`.
Why don't you implement your own `shouldComponentUpdate()`?

**Comment by mindjuice** [comment]
I know that this case is currently not covered by the code, which is why I am suggesting a possible enhancement.

I want to avoid creating a custom ``shouldComponentUpdate()`` function every time that I want to pass in an array or an object constant.

My component is still pure, and the values of the props are still "the same".

I can implement this myself over top of ``react-pure-render``, which is probably what I will do, but I wanted to see if anyone else using ``react-pure-render`` might have the same need.

**Comment by gaearon** [comment]
This sounds out of scope and exactly the case where you’d want to either write a custom `shouldComponentUpdate()` or use something like [Reselect](https://github.com/reactjs/reselect) to memoize computations.

In any case, I am deprecating this project, so I am closing this.
