### ISSUE TITLE
@PureRender class decorator

### ISSUE THREAD

**Issue by taion** [gaearon/react-pure-render#2]
In the interest of completeness/tidiness, one other somewhat plausible option would be to expose an `@PureRender` class decorator that would do something appropriate, per https://github.com/wycats/javascript-decorators#class-declaration.

I think I like this syntax a little more than the "function" syntax, and it's Babel stage 1 instead of stage 0. It'd look a bit like

```jsx
import PureRender from 'react-pure-render/decorator';

@PureRender
class MyComponent extends React.Component {
  ...
}
```

What do you think?

**Comment by gaearon** [comment]
I'm happy to accept a PR adding this.

**Comment by jeffbski** [comment]
One can use this for inspiration https://github.com/brigand/react-purerender/blob/master/index.js

**Comment by bvaughn** [comment]
(Also related: https://github.com/felixgirault/pure-render-decorator)

**Comment by taion** [comment]
I consider this package to largely be superseded by https://github.com/facebook/react/pull/3355, which will also give flexibility to compare `context`, so I'm closing this PR for now.
