### ISSUE TITLE
`shallowEqual` gives false positives for `NaN`s

### ISSUE THREAD

**Issue by adrianton3** [gaearon/react-pure-render#21]
This happens because properties are checked with `!==` for equality (`objA[keysA[i]] !== objB[keysA[i]]`). `Object.is` would be a more correct alternative.

`NaN` is usually the result of buggy code but it might be used as "undefined-value" in some huge finance table full of data.

**Comment by gaearon** [comment]
Yep. Please see my reply in https://github.com/gaearon/react-pure-render/issues/25#issuecomment-195842972.
