### ISSUE TITLE
shallow-equal: Custom comparison for Date objects?

### ISSUE THREAD

**Issue by Strate** [gaearon/react-pure-render#25]
Date objects almost anytime created as new instances.
I.e., I received a message from a socket with an entity object, contains date in some field.
I perform a conversion from ISO string to Date object.
Then I am trying to compare two objects through `shallowEquals`, and always get `false`, because there is always two different instances of `Date`.

One of solution is implementing a storage for Date objects and reuse them when converting ISO string, but this definetely gives an memory leaking.

Making custom compare for Date objects could be a solution.

**Comment by gaearon** [comment]
I don’t plan to fix it, but I think [`react-addons-shallow-compare`](https://facebook.github.io/react/docs/shallow-compare.html) is going to have a fix for this in v15. I encourage you to use it instead, as I am deprecating this project.
