### ISSUE TITLE
Any Ideas on how to get eslint-plugin-react linting with PureComponent?

### ISSUE THREAD

**Issue by export-mike** [gaearon/react-pure-render#27]
Hey,

thanks for this really useful component. I'm finding that when I use PureComponent the linting on propTypes etc they no longer work as I'm not extending React.Component... I guess we need another ```eslint-plugin-react-pure-render``` plugin? Any ideas?

**Comment by gaearon** [comment]
I encourage you to stop using `PureComponent` and either use `react-pure-render/function` or, better, start using the official [`react-addons-shallow-compare`](https://facebook.github.io/react/docs/shallow-compare.html). I am deprecating this package in favor of it.
