### ISSUE TITLE
PureComponent clarification

### ISSUE THREAD

**Issue by steida** [gaearon/react-pure-render#6]
"My suggestion for now is to use pure components in apps relying on such libraries very carefully, and only use pure rendering for leaf-ish components that are known not to rely on any parent context."

I tried that in my github.com/steida/este stack and on private much bigger app. The result is: Once you are using PureComponents, you wan't to use PureComponents only and nothing else.

The problem with mixing classic and PureComponents is complexity. Sonner or later something will not rerender, and you have to debug props and stores getters to figure out why. PureComponents are appealing, and simple rule "leaf-ish components" is too simple. I would add sentence "If your app state is modeled with immutable.js, the good practise is using PureComponents only. And then we need context workaround I'm using in Este.

**Comment by steida** [comment]
Feel free to close it as irrelevant :-)

**Comment by gaearon** [comment]
I'm totally for using pure components only, that's what I do in my apps.

However it's too tricky to explain the context issue in README. Your workaround only works for React Router, not for many other libs that use context. This is very unexpected for the beginners.

Those who are interested in this will read about the context issue anyway and figure out the workarounds on their own like you did. For the rest, the warning will help avoid some headaches.
